name: build-docker-image
on:
    push:
        paths:
            - "dockerfiles/**"
env:
    image_tag: xmars/birt-report:4.15.0

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build & Publish image
              run: |
                  cd ${{ github.workspace }}/dockerfiles
                  docker build -t ${{ env.image_tag }} .
                  docker push ${{ env.image_tag }}
